[package]
name = "cube"
version = "0.1.0"
authors = ["Paarth Madan <paarth.madan@shopify.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.0.0"
rand = "0.7"
